=== grimdarkscaling/metrology/schemas/prime_marine_part.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://grimdarkscaling.com/schemas/prime_marine_part.schema.json",
  "title": "Part",
  "description": "A Part from a Space Marine Prime Kit",
  "type": "object",
  "properties": {
    "partName": {
      "description": "A short description name for a kit part",
      "type": "string"
    },
    "dimensions": {
      "type": "object",
      "properties": {
        "partHeight": {
          "description": "Height in millimeters for the part",
          "type": "number"
        },
        "partWidth": {
          "description": "Width in millimeters for the part",
          "type": "number"
        },
        "partLength": {
          "description": "Length in millimeters for the part",
          "type": "number"
        }
      }
    },
    "partNotes": {
      "description": "Additional context on the part measurements",
      "type": "string"
    },
    "partParentKit": {
      "description": "Name of Manufacturer's Kit containing the part",
      "type": "string"
    },
    "partMeasurementMethod": {
      "description": "Detailed information on how the measurement was taken. Measuring Tools used, elements used as referece (e.g. 'width measured from arm socket to arm socket')",
      "type": "string"
    },
    "tags": {
      "description": "list of tags for ease of searching and filtering",
      "type": "array",
      "items": {
        "type": "string"
      },
      "uniqueItems": true
    }
  }
}

=== grimdarkscaling/metrology/data/prime_blah.json
{
  "partName": "Aggressor Sergeant Torso Front",
  "dimensions": {
    "partHeight": 6.2,
    "partWidth": 4.8,
    "partLength": 2.6
  },
  "partNotes": "This is a test part and measurements are inaccurate!!",
  "partParentKit": "Primaris Aggressor",
  "partMeasurementMethod": "Height measured from top of neck collar to bottom of belly creases",
  "tags": ["fake", "testing", "alpha", "gw", "prime", "test"]
}
